/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/globalComponents/NavBar/index.vue')['default']
    NoData: typeof import('./src/components/globalComponents/NoData/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/globalComponents/SvgIcon/index.vue')['default']
    TabBar: typeof import('./src/components/globalComponents/TabBar/index.vue')['default']
    TabNav: typeof import('./src/components/globalComponents/TabNav/index.vue')['default']
    TestGlobal: typeof import('./src/components/globalComponents/TestGlobal/index.vue')['default']
    VideoPlayer: typeof import('./src/components/globalComponents/VideoPlayer/index.vue')['default']
  }
}
